language: node_js
node_js:
- '6.1'
deploy:
  provider: npm
  email: webmaster-private@kth.se
  api_key:
    secure: MgZ163c0OTLCYzrL4/xh2Pp6l9elQtOF3s19erDlVLgLoFbsTMMfsDDV5iVg6VbRDwi+TIAaLELnFcPYiMOSoxoYKqAN7poT7eObEpw6cSL4ekyJj6TWn6GD2XGObNhvmOoIcuniIzBplpj2pjdMFj2o/oNl0VsLHzE+QrkSZSVshWYTo4PXf8GQ3BYFkkpMY/tnmkHSGtyay0fIko8j9UBxN/TWGXNCYYaEjM3VvEVt+O39IWX3TMha2QouzElToilav576f315RNCzyGANBBw5ZG8NNcuP2iR9ITsx+6aUUcQEbVatE83vdvE4NBBQtX+wFZvrk9fhkDHUepnARSNg+wVcWSo2w8pR8xBnihKEY4Ad8WvEanhmZfq0zeEciulN9BOU508MjhHYOgNTxjwmuMZ4aVorUgZ6LM1u9YJdiU46yU6kOOh/uyWe4lZVgKctkcH5aXioKa2Us618Z7zzMVAUAfkCJrAwG6cRMpnCR6E1YR1RwDuqQOMe/Q2mhjwKG5PZz+Q996KH61vsQC2I1DCUf99SO3dR7cF0UUNUSTkxkoqXNWqLPVxXv2O9m8o1gSgU5lYrrke9DaagVyW8nm8PysjobLXKnpXzHwxD96MH2K6/wyGO/DuZLfyM+5SJDEPaW0dl05F462nTHU5CCDvszRs7CRT6wXSZ7Ec=
  on:
    tags: true
    repo: KTH/kth-node-cortina-block
notifications:
  slack:
    secure: O8lnieCIj/2C77gmckgIGGr8ZuVP7DdRt1g2JXttzH2ut/g/CfNglwR9SoVQKZnmnPsx0gCeoUfccuOD8QjKg5CjvoG3RJmWIYmVA2nbKmmvK+FeE8ipPEYFvgV3OmrmUF73g5/WEeh6uMrpO/HNNE9pnrvVMEvpxPzxnwcgfPTJytVg3Qx5RTWM21mSiJMzmGTYtqgG0bSd0Syzas7TWIFLOgw9OGE6olGknyPmdKRM5K59V7RBC1ZfGuFK2+d/aW8v6SmJee/oy9ugWqDgjDO/oLsbfJXhQ3qqs7p/CAdvGMdVHZOSK772Ryi3U1pbCaA9jtt1P6wPsbjwhzIMDmMHzvFir0oL1QYLd+TIuCx29KO63xHJjUhueAHvC3FxyJICvQ6o9dfrV1lYLzJ9QGO7q1YTNzdjyA5CPJE3PtOI2c36UQcSRy2rNoAYPftlSZIsziqnv30EJ7jDfDVTZOxKnN1vdf5/ennJHwX/vGgrnMnUVesvn3y2sMGxWc4xmPYn3zSSnO6LNt+6ScD97zzxWCdCIEfPBNKkxMpT9quSPbOglpe0HAmuXe3Hj1Vp9HANUsJ22f1GTFsvUpjnb2LLR3iXxdXdf9P+J7poZxy5WAmkQc84LhCQAQDcEzNzhmSfmE2z8tGbv8qRmlCggoQbSUGe+oKKKs30rMBJhN4=
