language: node_js
node_js:
- '6.1'
deploy:
  provider: npm
  email: webmaster-private@kth.se
  api_key:
    secure: Wsymto6A+4LvAKEPflxCKUgjmaYmFxZ+rwoI/LJgqii/5hf1unGT+CoWWj7h0HraxTLgLx+7l9G9/z+ThrY2qZK/xjBjzv9T/I3eainhHXcNG5ZI7Ln6NpNFUpvi81nyc2ehr0nIexRatr6gdYa9vVAKUf20yAFp+vjuP99s2F+U21nwPcM1/Jfzn8IS9dQl1c2BSnuqRzuG51tapUeL9txbD0KQwjAIUjdEswbtkh+TEAhOlw0c4dOKv39nCLAXVh6erRR3N4AxkWzxZzYaaySHrVC6wF58rzPIoH4pv4Ph8a19iwdkgwJ+35FWONvZmBt+wusmpH4VVWKu2YAurtNx72qsmnh6QxZmRKHiHo3FWq+nwBWTy9QyjVe9ShjaDY+BuZ9X/XmVMsodV2Xm3qi09d1rjHjR6lwSs0V284e94rPeacyXI7k85Za91hVcsL9tkEU3z9FxzS4htf+ahCN31dm3LYuCNzUZAya5iBmQNFaI8ZgfOilf3mKyd8QDFklb5XisgDfQjM/Vlw+8gq/N9Hsz5tunvL9fEnQ6B7mbbsmx3NX9SUbdFdJOg5mApN+rCF6v/Yar+17aTbKmjigqruOX+zOOu6w3IVwtkmn1YPFdu38/R6n1VXrC8dY48JUv1I25bPXwrpSfTsj2yffoHIdvJia6R53HTwY6Shk=
  on:
    repo: KTH/kth-node-cortina-block
    branch: master
notifications:
  slack:
    secure: O8lnieCIj/2C77gmckgIGGr8ZuVP7DdRt1g2JXttzH2ut/g/CfNglwR9SoVQKZnmnPsx0gCeoUfccuOD8QjKg5CjvoG3RJmWIYmVA2nbKmmvK+FeE8ipPEYFvgV3OmrmUF73g5/WEeh6uMrpO/HNNE9pnrvVMEvpxPzxnwcgfPTJytVg3Qx5RTWM21mSiJMzmGTYtqgG0bSd0Syzas7TWIFLOgw9OGE6olGknyPmdKRM5K59V7RBC1ZfGuFK2+d/aW8v6SmJee/oy9ugWqDgjDO/oLsbfJXhQ3qqs7p/CAdvGMdVHZOSK772Ryi3U1pbCaA9jtt1P6wPsbjwhzIMDmMHzvFir0oL1QYLd+TIuCx29KO63xHJjUhueAHvC3FxyJICvQ6o9dfrV1lYLzJ9QGO7q1YTNzdjyA5CPJE3PtOI2c36UQcSRy2rNoAYPftlSZIsziqnv30EJ7jDfDVTZOxKnN1vdf5/ennJHwX/vGgrnMnUVesvn3y2sMGxWc4xmPYn3zSSnO6LNt+6ScD97zzxWCdCIEfPBNKkxMpT9quSPbOglpe0HAmuXe3Hj1Vp9HANUsJ22f1GTFsvUpjnb2LLR3iXxdXdf9P+J7poZxy5WAmkQc84LhCQAQDcEzNzhmSfmE2z8tGbv8qRmlCggoQbSUGe+oKKKs30rMBJhN4=
